# Generated by Django 3.1 on 2020-08-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
