# Generated by Django 3.1 on 2020-08-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_advert_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='baner/')),
                ('url', models.CharField(max_length=350)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
